cmake_minimum_required(VERSION 3.21)

# Requires CMake 3.21 (the project minimum): COPY_FILE ONLY_IF_DIFFERENT.
if(NOT DEFINED SOURCE_TREE OR NOT DEFINED DESTINATION_TREE)
    message(FATAL_ERROR "SOURCE_TREE and DESTINATION_TREE are required")
endif()
if(NOT IS_DIRECTORY "${SOURCE_TREE}")
    message(FATAL_ERROR "Missing source tree: ${SOURCE_TREE}")
endif()
file(REAL_PATH "${SOURCE_TREE}" source)
file(REAL_PATH "${DESTINATION_TREE}" destination)
cmake_path(IS_PREFIX source "${destination}" NORMALIZE destination_in_source)
cmake_path(IS_PREFIX destination "${source}" NORMALIZE source_in_destination)
if(destination_in_source OR source_in_destination)
    message(FATAL_ERROR "Runtime source and destination trees must not overlap")
endif()
file(MAKE_DIRECTORY "${destination}")
file(GLOB_RECURSE old_files RELATIVE "${destination}" LIST_DIRECTORIES false "${destination}/*")
foreach(relative IN LISTS old_files)
    if(NOT EXISTS "${source}/${relative}")
        file(REMOVE "${destination}/${relative}")
    endif()
endforeach()
file(GLOB_RECURSE source_files RELATIVE "${source}" LIST_DIRECTORIES false "${source}/*")
foreach(relative IN LISTS source_files)
    get_filename_component(parent "${destination}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY_FILE "${source}/${relative}" "${destination}/${relative}" ONLY_IF_DIFFERENT)
endforeach()
